server:
  port: 8081

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: scott
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    database: 2
  jpa:
    show-sql: true

mybatis:
  type-aliases-package: com.li.design.entity
  mapper-locations: classpath:mapper/*.xml
